### ISSUE TITLE
Wither can still break blocks

### ISSUE THREAD

**Issue by Laifsyn** [globalista-dev/Fabric-Reinforced-Obsidian#1]
fabric-romod-1.18.1-1.1.0
Fabric 0.13.3

The wither can still break the reinforced glass and tinted glass. Also the Iron Bars(unless intended to not resist wither attacks)

**Comment by Laifsyn** [comment]
![image](https://user-images.githubusercontent.com/99366187/160222538-86d8bf36-67b3-472d-ba25-bcf92e029eea.png)

**Comment by globalista-dev** [comment]
The Dark Iron Bars shouldn't be immune, that's intentional. However the glass should. I forgot to change the default blast resistance values. My bad. Should be fixed on 1.1.1, available for 1.18.1 and 1.18.2.
