### ISSUE TITLE
Unable to craft reinforced iron bars.

### ISSUE THREAD

**Issue by Zarepheth** [globalista-dev/Fabric-Reinforced-Obsidian#3]
Mod file: fabric-romod-1.19.2-1.2.2.jar
Minecraft version: 1.19.2
CurseForge Overwolf profile based upon "[Better MC [FABRIC]](https://www.curseforge.com/minecraft/modpacks/better-mc-fabric)", though I've added a bunch of additional mods (_and disabled a few that came with it)_.

I do not see a crafting recipe in REI. Trying all possible combinations of 5 iron ingots and one netherite ingot in the standard iron bars recipe does not work.
```
I - N - I
I - I - I
```
I also experimented with combining iron bars or iron blocks with netherite ingot in anvil and smithing table.

Currently, REI shows that I must uncraft the reinforced obsidian or reinforced glass from this mod to make the reinforced iron bars. (_The mod pack has Twilight Forest, which has an uncrafting table._) 

Is there a different recipe? 
I have the [Polymorph (Fabric) ](https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric)mod also installed, so recipe conflicts ought to give me an option to select the result I want.

**Comment by globalista-dev** [comment]
I missed a recipe error! Thanks for pointing it out. The recipe is indeed what you thought it was.

Should be fixed on version 1.19.2-1.2.3. If it's not up on CurseForge, you can find it here on GitHub.
